name: Build and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment:
      # This is required to deploy to GitHub Pages
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-latest

    steps:
    - name: Checkout repository 🛎️
      uses: actions/checkout@v4

    - name: Set up Xcode (specify version)
      run: |
        sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
        sudo xcodebuild -license accept

    - name: Build documentation for SwiftInPocket
      run: |
        xcodebuild docbuild -scheme SwiftInPocket -derivedDataPath /tmp/docbuild -destination 'generic/platform=iOS'
      
    - name: Process documentation for SwiftInPocket
      run: |
        $(xcrun --find docc) process-archive transform-for-static-hosting /tmp/docbuild/Build/Products/Debug-iphoneos/SwiftInPocket.doccarchive --output-path docs --hosting-base-path SwiftInPocket
        echo "<script>window.location.href += \"/documentation/swiftinpocket\"</script>" > docs/index.html

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: 'docs'  # Upload only the docs directory

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
